import { prisma } from "@/lib/db/prisma";

const jobSelect = {
  id: true,
  reference: true,
  status: true,
  tonnage: true,
  distanceKm: true,
  ratePerTonne: true,
  totalNet: true,
  pickupFrom: true,
  pickupTo: true,
  deliverBy: true,
  acceptedAt: true,
  createdAt: true,
  carrier: {
    select: {
      id: true,
      name: true,
      logoUrl: true,
      // Licences on file: the buyer judges a carrier on these.
      _count: { select: { carrierDocuments: true } },
    },
  },
  pickupLocation: { select: { city: true, postalCode: true, voivodeship: true } },
  deliveryLocation: { select: { city: true, postalCode: true, voivodeship: true } },
  purchase: {
    select: {
      reference: true,
      status: true,
      id: true,
      buyer: { select: { id: true, name: true } },
      offer: { select: { grainType: true, reference: true, farmer: { select: { id: true, name: true } } } },
    },
  },
} as const;

type JobRow = Awaited<
  ReturnType<typeof prisma.transportJob.findMany<{ select: typeof jobSelect }>>
>[number];

function toDto(job: JobRow) {
  return {
    id: job.id,
    reference: job.reference,
    status: job.status,
    tonnage: job.tonnage.toString(),
    distanceKm: job.distanceKm,
    ratePerTonne: job.ratePerTonne?.toString() ?? null,
    totalNet: job.totalNet?.toString() ?? null,
    pickupFrom: job.pickupFrom,
    pickupTo: job.pickupTo,
    deliverBy: job.deliverBy,
    acceptedAt: job.acceptedAt,
    createdAt: job.createdAt,
    carrierId: job.carrier?.id ?? null,
    carrierName: job.carrier?.name ?? null,
    carrierLogoUrl: job.carrier?.logoUrl ?? null,
    carrierDocumentCount: job.carrier?._count.carrierDocuments ?? 0,
    fromCity: job.pickupLocation.city,
    fromPostalCode: job.pickupLocation.postalCode,
    fromVoivodeship: job.pickupLocation.voivodeship,
    toCity: job.deliveryLocation.city,
    toPostalCode: job.deliveryLocation.postalCode,
    toVoivodeship: job.deliveryLocation.voivodeship,
    purchaseReference: job.purchase.reference,
    purchaseStatus: job.purchase.status,
    purchaseId: job.purchase.id,
    buyerId: job.purchase.buyer.id,
    buyerName: job.purchase.buyer.name,
    farmerId: job.purchase.offer.farmer.id,
    farmerName: job.purchase.offer.farmer.name,
    grainType: job.purchase.offer.grainType,
    offerReference: job.purchase.offer.reference,
  };
}

export type TransportJobDto = ReturnType<typeof toDto>;

/** The freight board — only jobs generated by a completed purchase. */
export async function listAvailableJobs() {
  const rows = await prisma.transportJob.findMany({
    where: { status: "AVAILABLE" },
    select: jobSelect,
    orderBy: { createdAt: "desc" },
  });
  return rows.map(toDto);
}

export async function listJobsByCarrier(carrierId: string) {
  const rows = await prisma.transportJob.findMany({
    where: { carrierId },
    select: jobSelect,
    orderBy: { acceptedAt: "desc" },
  });
  return rows.map(toDto);
}

/**
 * Runs carrying this farmer's grain, once somebody is actually driving them.
 *
 * The farmer loads the truck, so the eligibility rules let them rate the
 * carrier — but until now nothing in the UI asked. Jobs with no carrier are
 * excluded: there is nobody to judge yet.
 */
export async function listJobsForFarmer(farmerId: string) {
  const rows = await prisma.transportJob.findMany({
    where: {
      carrierId: { not: null },
      purchase: { offer: { farmerId } },
    },
    select: jobSelect,
    orderBy: { acceptedAt: "desc" },
  });
  return rows.map(toDto);
}

/** Carriers who put themselves forward and are waiting on this buyer. */
export async function listJobsAwaitingApproval(buyerId: string) {
  const rows = await prisma.transportJob.findMany({
    where: { status: "ASSIGNED", purchase: { buyerId } },
    select: jobSelect,
    orderBy: { acceptedAt: "desc" },
  });
  return rows.map(toDto);
}

export async function listAllJobs() {
  const rows = await prisma.transportJob.findMany({
    select: jobSelect,
    orderBy: { createdAt: "desc" },
  });
  return rows.map(toDto);
}
